export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAIL = 'POSTS_FAIL';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
